"""Reusable docs payloads for the external integration API."""

from __future__ import annotations

import json
from typing import Any

from app.config import settings

INTEGRATION_DOCS_TAG_DESCRIPTION = """
Public documentation endpoints for external Donkey SEO clients.
"""

INTEGRATION_ARTICLES_TAG_DESCRIPTION = """
API-key protected content endpoints intended for machine-to-machine integrations.
"""

INTEGRATION_CLIENT_ENV_VARS: dict[str, str] = {
    "DONKEY_SEO_API_KEY": (
        "Project integration API key. Generate it in the Donkey SEO dashboard and send it as "
        "X-API-Key when calling protected integration routes."
    ),
    "DONKEY_SEO_WEBHOOK_SECRET": (
        "Project webhook signing secret. Generate or rotate it in the Donkey SEO dashboard and "
        "use it to verify X-Donkey-Signature on webhook requests."
    ),
}

INTEGRATION_CLIENT_ENV_TEMPLATE = """
# Donkey SEO client integration credentials
# Generate both values in the Donkey SEO dashboard for the target project.
DONKEY_SEO_API_KEY=replace-with-project-integration-api-key
DONKEY_SEO_WEBHOOK_SECRET=replace-with-project-webhook-signing-secret
"""

MODULAR_DOCUMENT_CONTRACT: dict[str, Any] = {
    "schema_version": "1.0",
    "seo_meta": {
        "h1": "Primary on-page headline",
        "meta_title": "Browser title / SERP title",
        "meta_description": "SERP meta description",
        "slug": "url-safe-slug",
        "primary_keyword": "primary keyword phrase",
    },
    "conversion_plan": {
        "primary_intent": "informational|commercial|transactional|navigational or custom value",
        "cta_strategy": [
            "Narrative CTA plan notes generated by Donkey SEO",
        ],
    },
    "author": {
        "id": "author_uuid",
        "name": "Author display name",
        "bio": "Author bio text",
        "social_urls": {
            "linkedin": "https://www.linkedin.com/in/example",
            "x": "https://x.com/example",
        },
        "basic_info": {
            "title": "Head of Content",
            "location": "Amsterdam",
        },
        "profile_image": {
            "object_key": "projects/<project_id>/authors/<author_id>/<sha256>.png",
            "mime_type": "image/png",
            "width": 512,
            "height": 512,
            "byte_size": 50221,
            "sha256": "<sha256>",
            "signed_url": "https://... (optional, short-lived, present on delivery/read payloads)",
        },
    },
    "featured_image": {
        "object_key": "projects/<project_id>/content-images/<brief_id>/<sha256>.png",
        "mime_type": "image/png",
        "width": 1200,
        "height": 630,
        "byte_size": 185422,
        "sha256": "<sha256>",
        "title_text": "Canonical image title text",
        "template_version": "1.0",
        "source": "llm_template_spec",
        "style_variant_id": "variant-hero-balance",
        "signed_url": "https://... (optional, short-lived, present on delivery/read payloads)",
    },
    "blocks": [
        {
            "block_type": (
                "hero|summary|section|list|comparison_table|steps|faq|cta|conclusion|sources"
            ),
            "semantic_tag": "header|section|aside|footer|table",
            "heading": "Optional heading text",
            "level": 2,
            "body": "Optional paragraph body",
            "items": ["List or steps items"],
            "ordered": False,
            "table_columns": ["Column A", "Column B"],
            "table_rows": [["cell 1", "cell 2"]],
            "faq_items": [{"question": "Q", "answer": "A"}],
            "cta": {
                "label": "Learn more",
                "href": "https://example.com",
                "target_brief_id": "brief_uuid (optional, deferred internal-link resolution)",
            },
            "links": [
                {
                    "anchor": "Anchor text",
                    "href": "https://example.com/resource",
                    "target_brief_id": "brief_uuid (optional, deferred internal-link resolution)",
                }
            ],
        }
    ],
}

MODULAR_DOCUMENT_FIELD_REFERENCE: dict[str, Any] = {
    "schema_version": "Contract version used by tolerant-reader parsing.",
    "seo_meta": {
        "description": "SEO metadata to map directly to page-level SEO fields.",
        "fields": {
            "h1": "Canonical on-page headline. Render one H1 only.",
            "meta_title": "SERP/browser title.",
            "meta_description": "SERP description.",
            "slug": "Canonical URL slug from Donkey SEO.",
            "primary_keyword": "Primary keyword strategy anchor.",
        },
    },
    "conversion_plan": {
        "description": "Narrative intent and CTA strategy hints for rendering and publishing.",
        "fields": {
            "primary_intent": "Intent classification for narrative and CTA tone.",
            "cta_strategy": "Ordered CTA strategy notes for editorial/publishing systems.",
        },
    },
    "author": {
        "description": "Optional byline metadata for article ownership and trust signals.",
        "fields": {
            "id": "Author identifier from Donkey SEO.",
            "name": "Display name.",
            "bio": "Byline bio snippet.",
            "social_urls": "Map of social platform names to URLs.",
            "basic_info": "Additional free-form profile metadata.",
            "profile_image": {
                "description": "Optional profile image metadata.",
                "fields": {
                    "object_key": "Private object-store key.",
                    "mime_type": "Image MIME type.",
                    "width": "Pixel width.",
                    "height": "Pixel height.",
                    "byte_size": "File size in bytes.",
                    "sha256": "File hash.",
                    "signed_url": (
                        "Short-lived read URL for retrieval only. Do not persist beyond transient "
                        "processing."
                    ),
                },
            },
        },
    },
    "featured_image": {
        "description": "Optional featured image metadata for OG/social/cms hero image usage.",
        "fields": {
            "object_key": "Private object-store key.",
            "mime_type": "Image MIME type.",
            "width": "Pixel width.",
            "height": "Pixel height.",
            "byte_size": "File size in bytes.",
            "sha256": "File hash.",
            "title_text": "Canonical image title text.",
            "template_version": "Template contract version used for generation.",
            "source": "Image generation source tag.",
            "style_variant_id": "Image style variant id.",
            "signed_url": (
                "Short-lived read URL for retrieval only. Do not persist beyond transient "
                "processing."
            ),
        },
    },
    "blocks": {
        "description": "Ordered content components. Preserve order and nested fields exactly.",
        "fields": {
            "block_type": "Block discriminator used for parser dispatch.",
            "semantic_tag": "Intended semantic HTML/container hint.",
            "heading": "Optional heading text.",
            "level": "Optional heading level (2-4 for heading blocks).",
            "body": "Optional paragraph text.",
            "items": "List items used by list/steps blocks.",
            "ordered": "Ordered-list hint for list blocks.",
            "table_columns": "Header labels for comparison tables.",
            "table_rows": "Row cells for comparison tables.",
            "faq_items": "Structured FAQ rows with question+answer.",
            "cta": {
                "description": "CTA payload primarily used by cta blocks.",
                "fields": {
                    "label": "CTA button/anchor label.",
                    "href": "CTA destination URL/path.",
                    "target_brief_id": (
                        "Optional unresolved internal-link target for deferred resolution."
                    ),
                },
            },
            "links": {
                "description": "Per-block links that preserve editorial placement context.",
                "item_fields": {
                    "anchor": "Anchor text.",
                    "href": "Destination URL/path.",
                    "target_brief_id": (
                        "Optional unresolved internal-link target for deferred resolution."
                    ),
                },
            },
        },
    },
}

MODULAR_BLOCK_TYPE_REFERENCE: dict[str, Any] = {
    "hero": {
        "purpose": "Top-of-page opener that carries the canonical article promise.",
        "best_handling": [
            "Render first.",
            "Use heading as H1 if present; ensure only one H1 exists overall.",
            "Keep body concise and aligned with primary intent.",
        ],
    },
    "summary": {
        "purpose": "Early scan-friendly overview of what the article covers.",
        "best_handling": [
            "Place near the top (usually after hero).",
            "Render as compact section with optional heading.",
            "Keep language scannable and non-redundant.",
        ],
    },
    "section": {
        "purpose": "General narrative section for the core article body.",
        "best_handling": [
            "Map to standard section component.",
            "Respect level for heading hierarchy (H2-H4).",
            "Preserve links and body text without reordering.",
        ],
    },
    "list": {
        "purpose": "Bulleted or ordered collection of related points.",
        "best_handling": [
            "Render items as UL/OL based on ordered.",
            "Preserve item order.",
            "Keep heading/body context around the list when provided.",
        ],
    },
    "comparison_table": {
        "purpose": "Structured side-by-side comparison data.",
        "best_handling": [
            "Render semantic table with table_columns as headers.",
            "Preserve row/column ordering exactly.",
            "Add accessibility semantics (caption/header associations) per frontend standard.",
        ],
    },
    "steps": {
        "purpose": "Ordered procedure where sequence carries meaning.",
        "best_handling": [
            "Render as ordered list/process component.",
            "Do not reorder or collapse steps.",
            "Keep links inline with the step context.",
        ],
    },
    "faq": {
        "purpose": "Question-answer block for objections and long-tail search intent.",
        "best_handling": [
            "Persist each FAQ item as structured Q/A.",
            "Render as accordion/details pattern if your system supports it.",
            "Keep question/answer fidelity for schema/export use.",
        ],
    },
    "cta": {
        "purpose": "Explicit conversion prompt with actionable destination.",
        "best_handling": [
            "Render cta.label + cta.href exactly when valid.",
            "Honor sequence placement unless your product has controlled CTA slots.",
            "Align with conversion_plan.cta_strategy for tone and intensity.",
        ],
    },
    "conclusion": {
        "purpose": "Terminal wrap-up that reinforces key outcome and next action.",
        "best_handling": [
            "Render near end.",
            "Keep recap concise and decision-oriented.",
            "Preserve links/CTA context for final action.",
        ],
    },
    "sources": {
        "purpose": "Citation/reference block for claims and compliance traceability.",
        "best_handling": [
            "Preserve links and anchor text as references.",
            "Keep near end unless your CMS has dedicated citations component.",
            "Store for audit and refresh workflows.",
        ],
    },
}

PUBLICATION_WEBHOOK_CONTRACT: dict[str, Any] = {
    "events": [
        {
            "event_type": "content.article.publish_requested",
            "description": (
                "Sent when Donkey SEO requests publication of the latest immutable article "
                "version."
            ),
            "payload_fields": {
                "event_id": "Stable idempotency key. Same value is reused across retries.",
                "event_type": "Webhook event type string.",
                "occurred_at": "RFC3339/ISO-8601 UTC timestamp when dispatch was attempted.",
                "project": {
                    "id": "Project id.",
                    "domain": "Project domain.",
                    "locale": "Primary locale.",
                },
                "article": {
                    "article_id": "Article id.",
                    "brief_id": "Linked brief id.",
                    "version_number": "Current immutable version number.",
                    "title": "Version title.",
                    "slug": "Version slug.",
                    "primary_keyword": "Version primary keyword.",
                    "proposed_publication_date": "ISO date or null.",
                },
                "modular_document": (
                    "Full modular document payload, including optional author and image metadata."
                ),
                "rendered_html": "Rendered fallback HTML snapshot.",
            },
        }
    ],
    "headers": {
        "Content-Type": "application/json",
        "X-Donkey-Event": "Event type (same value as payload.event_type).",
        "X-Donkey-Delivery-Id": "Delivery id for operational tracing.",
        "X-Donkey-Timestamp": "Unix timestamp (seconds).",
        "X-Donkey-Signature": "HMAC signature in format sha256=<hex_digest>.",
    },
    "signature_verification": {
        "algorithm": "HMAC SHA256",
        "message_format": "{X-Donkey-Timestamp}.{raw_request_body}",
        "secret_env_var": "DONKEY_SEO_WEBHOOK_SECRET",
    },
    "delivery_policy": {
        "success_condition": "Any 2xx response",
        "retry_on": "Network errors and non-2xx responses",
        "max_attempts": 5,
        "backoff_seconds_after_attempt": [60, 120, 240, 480],
    },
}

MODULAR_DOCUMENT_CONTRACT_JSON = json.dumps(
    MODULAR_DOCUMENT_CONTRACT,
    indent=2,
    sort_keys=True,
)

INTEGRATION_PUBLIC_BASE_PATH = settings.versioned_integration_api_prefix

INTEGRATION_API_DESCRIPTION = """
Donkey SEO integration API for external programs.

This API is split into:
- public docs/guide routes (no authentication)
- API-key protected content routes for machine-to-machine article retrieval,
  pillar navigation retrieval, and publication callbacks

Core client contract:
- Donkey SEO is the source of truth for immutable article versions.
- Your integration fetches versions, preserves `modular_document` structure,
  publishes to your CMS/viewer, and reports publication state back.

Agent execution recommendation:
- If your agent supports planning mode, start in planning mode before changing code.
- Use planning mode to define storage schema, parser behavior, webhook handling,
  pillar/disambiguation routing, and publication callback updates before implementation.
- After planning, execute the approved implementation plan.

How pillar taxonomy works:
- Fetch project pillars from `GET __INTEGRATION_BASE_PATH__/pillars`.
- Use pillars as category/navigation primitives in your frontend.
- Main-page requirement: render active pillars in the footer as links to
  disambiguation pages (for example `/pillars/{pillar.slug}` or your CMS equivalent).
- Article list responses include `primary_pillar`, `secondary_pillars`, and
  `pillar_assignment_confidence` to support navigation and grouping.

How `modular_document` works:
- It is the canonical structured article payload, not just plain text.
- Top-level keys include:
  - `schema_version`
  - `seo_meta` (`h1`, `meta_title`, `meta_description`, `slug`, `primary_keyword`)
  - `conversion_plan` (`primary_intent`, `cta_strategy`)
  - optional `author` and optional `featured_image`
  - ordered `blocks[]`
- `blocks[]` is parsed by `block_type` (never by position).
- Supported `block_type` values:
  `hero`, `summary`, `section`, `list`, `comparison_table`,
  `steps`, `faq`, `cta`, `conclusion`, `sources`.
- Preserve order and nested structures (`faq_items`, `cta`, `links`,
  `table_columns/table_rows`) exactly.
- Signed image URLs in `author.profile_image.signed_url` and
  `featured_image.signed_url` are short-lived and should not be stored durably.

How publication webhooks work:
- Outbound event type: `content.article.publish_requested`.
- Payload includes:
  - `event_id`, `event_type`, `occurred_at`
  - `project` (`id`, `domain`, `locale`)
  - `article` (`article_id`, `brief_id`, `version_number`, `title`, `slug`,
    `primary_keyword`, `proposed_publication_date`)
  - `modular_document`
  - `rendered_html`
- Headers include:
  - `X-Donkey-Event`
  - `X-Donkey-Delivery-Id`
  - `X-Donkey-Timestamp`
  - `X-Donkey-Signature`
- Verify signature with HMAC SHA256 over:
  `{X-Donkey-Timestamp}.{raw_request_body}`
  using `DONKEY_SEO_WEBHOOK_SECRET`.
- Delivery policy:
  - success on any 2xx
  - retries on network/non-2xx errors
  - max 5 attempts
  - exponential backoff: 60s, 120s, 240s, 480s
- Use `event_id` as idempotency key.

Credentials for client implementers:
- `DONKEY_SEO_API_KEY`: send as `X-API-Key` on protected routes.
- `DONKEY_SEO_WEBHOOK_SECRET`: verify webhook signatures.
- Generate both in the Donkey SEO dashboard for the target project.

Full implementation guide:
- `GET __INTEGRATION_BASE_PATH__/guide/donkey-client`
""".replace("__INTEGRATION_BASE_PATH__", INTEGRATION_PUBLIC_BASE_PATH)

DONKEY_CLIENT_GUIDE_MARKDOWN = """
# Donkey SEO Client Implementation Guide (For Agents and Engineers)

Use this guide if you are building a Donkey SEO client with or without LLM coding.
Goal: ingest immutable article versions, preserve structured content exactly, publish via
CMS/viewer, and report publication state back to Donkey SEO.

## 0) Agent Workflow (Planning Mode First)

If your coding agent supports planning mode, start in planning mode before implementation.
Plan at least:
- immutable storage model and version keying,
- parser mapping for `modular_document` block types,
- webhook validation + retry/idempotency handling,
- pillar/disambiguation page wiring and footer link rendering,
- publication status PATCH flow.

Then implement the approved plan.

## 1) Credentials and Environment Variables

Use these environment variables in your client config or `.env.example`:

```env
DONKEY_SEO_API_KEY=replace-with-project-integration-api-key
DONKEY_SEO_WEBHOOK_SECRET=replace-with-project-webhook-signing-secret
```

How to obtain values:
- Generate both values from the Donkey SEO dashboard for the project you are integrating.
- `DONKEY_SEO_API_KEY` is used as `X-API-Key` on protected integration routes.
- `DONKEY_SEO_WEBHOOK_SECRET` is used only by your webhook receiver to validate
  `X-Donkey-Signature`.

## 2) Endpoints To Implement

Production API base URL:
- `https://api.donkeyseo.io`

How to compose endpoint URLs:
- All route templates below are relative paths.
- Production calls should use `https://api.donkeyseo.io` + route path.
- Example: `https://api.donkeyseo.io/api/v1/integration/articles?project_id=...`

- `GET __INTEGRATION_BASE_PATH__/articles?project_id={project_id}&page={page}&page_size={page_size}`
  - Returns a lightweight paginated list for article selection/sync.
- `GET __INTEGRATION_BASE_PATH__/pillars?project_id={project_id}&include_archived={bool_optional}`
  - Returns pillar categories plus assignment/article counts for navigation UIs.
- `GET __INTEGRATION_BASE_PATH__/article/{article_id}?project_id={project_id}`
  - Returns latest immutable article version.
- `GET __INTEGRATION_BASE_PATH__/article/{article_id}/versions/{version_number}`
  `?project_id={project_id}`
  - Returns explicit immutable version.
- `PATCH __INTEGRATION_BASE_PATH__/article/{article_id}/publication?project_id={project_id}`
  - Receives publication status updates from your CMS/blog integration.

Publication callback payload fields:
- `publish_status` (`scheduled|published|failed`)
- `published_at` (ISO datetime, required when `publish_status=published`)
- `published_url` (URL, required when `publish_status=published`)

Pillar navigation requirement:
- You MUST render active pillars in the footer of the main page.
- Each footer pillar link should point to a disambiguation page for that category.
- Recommended URL shape: `/pillars/{pillar.slug}` (or your CMS equivalent).

Example endpoint response payloads:

`GET __INTEGRATION_BASE_PATH__/articles?project_id=proj_123&page=1&page_size=2`
```json
{
  "items": [
    {
      "id": "c38f848d-66d6-4c47-b89a-30aa5a6dc881",
      "project_id": "proj_123",
      "brief_id": "ddf6c8d8-7a7c-4cf8-b7d8-8f84a80af872",
      "title": "How to Scale Programmatic SEO Content",
      "slug": "how-to-scale-programmatic-seo-content",
      "primary_keyword": "programmatic seo",
      "current_version": 3,
      "status": "approved",
      "publish_status": "published",
      "published_at": "2026-03-02T09:32:14Z",
      "published_url": "https://example.com/blog/programmatic-seo",
      "primary_pillar": {
        "id": "pillar_support",
        "name": "Support Automation",
        "slug": "support-automation"
      },
      "secondary_pillars": [
        {
          "id": "pillar_workflows",
          "name": "Workflow Integrations",
          "slug": "workflow-integrations"
        }
      ],
      "pillar_assignment_confidence": 0.82,
      "created_at": "2026-02-28T16:04:01Z",
      "updated_at": "2026-03-02T09:32:14Z"
    }
  ],
  "total": 47,
  "page": 1,
  "page_size": 2
}
```

`GET __INTEGRATION_BASE_PATH__/pillars?project_id=proj_123`
```json
{
  "items": [
    {
      "id": "pillar_support",
      "project_id": "proj_123",
      "name": "Support Automation",
      "slug": "support-automation",
      "description": "Customer support process and automation topics.",
      "status": "active",
      "source": "auto",
      "locked": false,
      "primary_brief_count": 11,
      "secondary_brief_count": 4,
      "total_brief_count": 15,
      "primary_article_count": 9,
      "published_primary_article_count": 6,
      "created_at": "2026-03-01T12:04:01Z",
      "updated_at": "2026-03-02T09:32:14Z"
    }
  ],
  "total": 1
}
```

`GET __INTEGRATION_BASE_PATH__/article/{article_id}?project_id={project_id}`
```json
{
  "id": "e3f99b38-f1e1-4e6b-8f43-f6eec13c1406",
  "article_id": "c38f848d-66d6-4c47-b89a-30aa5a6dc881",
  "project_id": "proj_123",
  "version_number": 3,
  "title": "How to Scale Programmatic SEO Content",
  "slug": "how-to-scale-programmatic-seo-content",
  "primary_keyword": "programmatic seo",
  "modular_document": {
    "schema_version": "1.0",
    "seo_meta": {
      "h1": "How to Scale Programmatic SEO Content",
      "meta_title": "Scale Programmatic SEO: A Practical Guide",
      "meta_description": "Operational workflow and architecture for scaling programmatic SEO.",
      "slug": "how-to-scale-programmatic-seo-content",
      "primary_keyword": "programmatic seo"
    },
    "conversion_plan": {
      "primary_intent": "informational",
      "cta_strategy": ["Offer implementation checklist at conclusion"]
    },
    "blocks": [
      {
        "block_type": "hero",
        "semantic_tag": "header",
        "heading": "How to Scale Programmatic SEO Content",
        "level": 1,
        "body": "A production-ready workflow for planning, generating, and publishing at scale."
      }
    ]
  },
  "rendered_html": "<h1>How to Scale Programmatic SEO Content</h1><p>...</p>",
  "qa_report": null,
  "status": "approved",
  "change_reason": "Expanded examples and tightened structure.",
  "generation_model": "gpt-5",
  "generation_temperature": 0.2,
  "created_by_regeneration": false,
  "created_at": "2026-03-02T08:54:07Z",
  "updated_at": "2026-03-02T09:14:55Z"
}
```

`PATCH __INTEGRATION_BASE_PATH__/article/{article_id}/publication?project_id={project_id}`
response:
```json
{
  "article_id": "c38f848d-66d6-4c47-b89a-30aa5a6dc881",
  "project_id": "proj_123",
  "publish_status": "published",
  "published_at": "2026-03-02T09:32:14Z",
  "published_url": "https://example.com/blog/programmatic-seo",
  "updated_at": "2026-03-02T09:32:15Z"
}
```

## 3) Immutable Storage Rules

Persist these fields for each version:
- `article_id`
- `project_id`
- `version_number`
- `title`
- `slug`
- `primary_keyword`
- `status`
- `modular_document` (store raw JSON unchanged)
- `rendered_html`
- `qa_report`
- `change_reason`
- `generation_model`
- `generation_temperature`
- `created_by_regeneration`
- `created_at`
- `updated_at`

Rules:
1. Use `(article_id, version_number)` as immutable key.
2. Never overwrite old versions.
3. Store raw payload before transformations.

## 4) Canonical `modular_document` Fields (All Known Fields)

Top-level keys:
- `schema_version`
- `seo_meta`
- `conversion_plan`
- `author` (optional)
- `featured_image` (optional)
- `blocks`

`seo_meta`:
- `h1`, `meta_title`, `meta_description`, `slug`, `primary_keyword`

`conversion_plan`:
- `primary_intent`
- `cta_strategy` (array)

`author` (optional):
- `id`, `name`, `bio`, `social_urls`, `basic_info`
- `profile_image` (optional):
  - `object_key`, `mime_type`, `width`, `height`, `byte_size`, `sha256`, `signed_url` (ephemeral)

`featured_image` (optional):
- `object_key`, `mime_type`, `width`, `height`, `byte_size`, `sha256`
- `title_text`, `template_version`, `source`, `style_variant_id`, `signed_url` (ephemeral)

`blocks[]` common keys:
- `block_type`, `semantic_tag`, `heading`, `level`, `body`
- `items`, `ordered`
- `table_columns`, `table_rows`
- `faq_items[]` with `question` + `answer`
- `cta` with `label`, `href`, optional `target_brief_id`
- `links[]` with `anchor`, `href`, optional `target_brief_id`

Signed URL rule:
- Never persist `featured_image.signed_url` or `author.profile_image.signed_url` as durable values.
- Treat signed URLs as short-lived read URLs for transient fetches only.

## 5) Block Purpose and Best Handling (No Ambiguity)

- `hero`
  - Purpose: top-of-page opener and primary promise.
  - Handling: render first, keep exactly one H1, keep concise intro.

- `summary`
  - Purpose: quick orientation block for scan-first readers.
  - Handling: place high on page, keep compact and readable.

- `section`
  - Purpose: core narrative section.
  - Handling: map to standard body section, honor heading `level` hierarchy.

- `list`
  - Purpose: grouped points.
  - Handling: render `items` as UL/OL based on `ordered`; preserve order.

- `comparison_table`
  - Purpose: side-by-side comparison.
  - Handling: render semantic table with headers; preserve all cells.

- `steps`
  - Purpose: sequence-driven procedure.
  - Handling: render as ordered process; never reorder steps.

- `faq`
  - Purpose: objection handling and FAQ search coverage.
  - Handling: keep Q/A structured; preserve wording fidelity.

- `cta`
  - Purpose: explicit conversion action.
  - Handling: use `cta.label` + `cta.href` directly; align with `conversion_plan.cta_strategy`.

- `conclusion`
  - Purpose: closing synthesis and final directional push.
  - Handling: keep near end; preserve recap + CTA context.

- `sources`
  - Purpose: references/citations for trust and compliance.
  - Handling: preserve anchors/URLs for traceability and audits.

## 6) Parsing Requirements

1. Parse by `block_type` (never by position).
2. Preserve block order exactly.
3. Preserve unknown fields in extension storage (do not silently drop).
4. Support optional/null fields with explicit safe defaults.
5. Keep pipeline auditable: raw payload -> normalized model -> publish payload.
6. Parser must be `schema_version` aware.
7. Add parser tests for every supported block type.

## 7) Webhook Events and Fields

Current outbound event set:
- `content.article.publish_requested`

Payload fields sent for this event:
- `event_id`, `event_type`, `occurred_at`
- `project` (`id`, `domain`, `locale`)
- `article` (`article_id`, `brief_id`, `version_number`, `title`, `slug`)
- `article` (`primary_keyword`, `proposed_publication_date`)
- `modular_document`
- `rendered_html`

Outbound headers:
- `X-Donkey-Event`
- `X-Donkey-Delivery-Id`
- `X-Donkey-Timestamp`
- `X-Donkey-Signature`

Signature verification:
1. Build message: `"{X-Donkey-Timestamp}.{raw_request_body}"`.
2. Compute `HMAC SHA256` using `DONKEY_SEO_WEBHOOK_SECRET`.
3. Compare with `X-Donkey-Signature` (`sha256=<hex_digest>`).

Delivery and retries:
- Success condition: any `2xx` response.
- Retries on network failures and non-`2xx` responses.
- Maximum 5 attempts.
- Backoff delays after failed attempts: 60s, 120s, 240s, 480s.

Idempotency:
- Use `event_id` as idempotency key.
- Duplicate `event_id` deliveries must be treated as retries.

Example webhook delivery (potential shape):

Headers:
```text
Content-Type: application/json
X-Donkey-Event: content.article.publish_requested
X-Donkey-Delivery-Id: pubwh_01JMR5V6QTYJ4S0P64F62Y43PM
X-Donkey-Timestamp: 1772446320
X-Donkey-Signature: sha256=33f1f2e40209f2f4b31bbf7dad0d13cc6fd41fb27690f58a1806dc4d2f0ab1f8
```

Body:
```json
{
  "event_id": "evt_01JMR5V6QAJ46R12VYAAW4M5A7",
  "event_type": "content.article.publish_requested",
  "occurred_at": "2026-03-02T09:32:00Z",
  "project": {
    "id": "proj_123",
    "domain": "example.com",
    "locale": "en-US"
  },
  "article": {
    "article_id": "c38f848d-66d6-4c47-b89a-30aa5a6dc881",
    "brief_id": "ddf6c8d8-7a7c-4cf8-b7d8-8f84a80af872",
    "version_number": 3,
    "title": "How to Scale Programmatic SEO Content",
    "slug": "how-to-scale-programmatic-seo-content",
    "primary_keyword": "programmatic seo",
    "proposed_publication_date": "2026-03-03"
  },
  "modular_document": {
    "schema_version": "1.0",
    "seo_meta": {
      "h1": "How to Scale Programmatic SEO Content",
      "meta_title": "Scale Programmatic SEO: A Practical Guide",
      "meta_description": "Operational workflow and architecture for scaling programmatic SEO.",
      "slug": "how-to-scale-programmatic-seo-content",
      "primary_keyword": "programmatic seo"
    },
    "conversion_plan": {
      "primary_intent": "informational",
      "cta_strategy": ["Offer implementation checklist at conclusion"]
    },
    "blocks": [
      {
        "block_type": "hero",
        "semantic_tag": "header",
        "heading": "How to Scale Programmatic SEO Content",
        "level": 1,
        "body": "A production-ready workflow for planning, generating, and publishing at scale."
      }
    ]
  },
  "rendered_html": "<h1>How to Scale Programmatic SEO Content</h1><p>...</p>"
}
```

## 8) End-to-End Client Flow

1. Receive webhook `content.article.publish_requested`.
2. Verify signature using `DONKEY_SEO_WEBHOOK_SECRET`.
3. Fetch latest/target article version with `DONKEY_SEO_API_KEY`.
4. Fetch project pillars from `GET __INTEGRATION_BASE_PATH__/pillars?project_id=...`.
5. Persist raw immutable payload.
6. Normalize `modular_document` and map blocks to CMS/viewer components.
7. Render main-page footer pillar links pointing to pillar disambiguation pages.
8. Publish/stage content.
9. PATCH publication status back to Donkey SEO.

## 9) Best-Practice Architecture (Recommended, Not Required)

Recommended publishing target:
1. If you have a CMS/blog platform, integrate Donkey SEO output into that CMS.
2. If you do not have a CMS, build an in-product article viewer component that matches
   your product design system and renders Donkey SEO blocks semantically.
3. Build pillar disambiguation pages and expose them via a footer section on the main page.
4. Keep footer links aligned with active pillars from `/integration/pillars`.

Recommended storage model:
1. Create an `article`/`blogpost` model in your database as the canonical local entity.
2. Store immutable Donkey SEO versions keyed by `(article_id, version_number)`.
3. Store mutable publication state separately (publish status, live URL, timestamps).

These are best-practice defaults. You can choose a different architecture if it better
fits your product constraints.

## 10) Documentation Access

- `GET __INTEGRATION_BASE_PATH__/guide/donkey-client`
  - Full implementation guide (markdown + structured JSON sections).
- `GET __INTEGRATION_BASE_PATH__/guide/donkey-client.md`
  - Markdown-only version of the same guide.
""".replace("__INTEGRATION_BASE_PATH__", INTEGRATION_PUBLIC_BASE_PATH)
