"""add blueprint_key and content_role fields

Revision ID: 3f0dba597dfa
Revises: 878310ff008b
Create Date: 2026-03-11 10:50:45.580676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0dba597dfa'
down_revision: Union[str, None] = '878310ff008b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brief_deltas', sa.Column('blueprint_key', sa.String(length=50), nullable=True, comment='Page type blueprint key from blueprints registry'))
    op.add_column('content_briefs', sa.Column('blueprint_key', sa.String(length=50), nullable=True, comment='Page type blueprint key from blueprints registry'))
    op.add_column('content_briefs', sa.Column('content_role', sa.String(length=30), nullable=True, comment='Content hierarchy role: pillar, supporting, or high_intent'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_briefs', 'content_role')
    op.drop_column('content_briefs', 'blueprint_key')
    op.drop_column('brief_deltas', 'blueprint_key')
    # ### end Alembic commands ###
