"""add projects per week

Revision ID: 775c3878190d
Revises: 6f937e4e0aa2
Create Date: 2026-03-04 13:36:32.507322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775c3878190d'
down_revision: Union[str, None] = '6f937e4e0aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('posts_per_week', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'posts_per_week')
    # ### end Alembic commands ###
