"""content pillars

Revision ID: e4e5d051eaeb
Revises: e2f3a4b5c6d7
Create Date: 2026-03-02 18:45:02.861538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e5d051eaeb'
down_revision: Union[str, None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_iteration_learnings_project_created_at'), table_name='discovery_iteration_learnings')
    op.drop_index(op.f('ix_pipeline_runs_parent_source_module'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_project_module_status'), table_name='pipeline_runs')
    op.drop_index(op.f('uq_pipeline_runs_content_dispatch_once'), table_name='pipeline_runs', postgresql_where="(((pipeline_module)::text = 'content'::text) AND (parent_run_id IS NOT NULL) AND (source_topic_id IS NOT NULL))")
    op.create_index(op.f('ix_pipeline_runs_parent_run_id'), 'pipeline_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_module'), 'pipeline_runs', ['pipeline_module'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_source_topic_id'), 'pipeline_runs', ['source_topic_id'], unique=False)
    op.alter_column('topics', 'serp_evidence_keyword_id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.models.base.StringUUID(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_topics_project_fit_rank'), table_name='topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_topics_project_fit_rank'), 'topics', ['project_id', 'fit_tier', 'priority_rank'], unique=False)
    op.alter_column('topics', 'serp_evidence_keyword_id',
               existing_type=app.models.base.StringUUID(length=32),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_pipeline_runs_source_topic_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_module'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_parent_run_id'), table_name='pipeline_runs')
    op.create_index(op.f('uq_pipeline_runs_content_dispatch_once'), 'pipeline_runs', ['parent_run_id', 'source_topic_id', 'pipeline_module'], unique=True, postgresql_where="(((pipeline_module)::text = 'content'::text) AND (parent_run_id IS NOT NULL) AND (source_topic_id IS NOT NULL))")
    op.create_index(op.f('ix_pipeline_runs_project_module_status'), 'pipeline_runs', ['project_id', 'pipeline_module', 'status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_parent_source_module'), 'pipeline_runs', ['parent_run_id', 'source_topic_id', 'pipeline_module'], unique=False)
    op.create_index(op.f('ix_discovery_iteration_learnings_project_created_at'), 'discovery_iteration_learnings', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
