"""

Revision ID: ef7ed32ca3a8
Revises: 
Create Date: 2026-02-13 11:05:48.569402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.base import StringUUID

# revision identifiers, used by Alembic.
revision: str = 'ef7ed32ca3a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('user_id', StringUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=10), nullable=False),
    sa.Column('primary_locale', sa.String(length=10), nullable=False),
    sa.Column('secondary_locales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('site_maturity', sa.String(length=20), nullable=True),
    sa.Column('maturity_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_goal', sa.String(length=100), nullable=True),
    sa.Column('secondary_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_cta', sa.String(length=255), nullable=True),
    sa.Column('topic_boundaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_budget_caps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caching_ttls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skip_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('brand_profiles',
    sa.Column('project_id', StringUUID(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('source_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('products_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('money_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('unique_value_props', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitor_positioning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_pains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('desired_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('restricted_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_scope_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('out_of_scope_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('project_id', StringUUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('paused_at_step', sa.Integer(), nullable=True),
    sa.Column('steps_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_step', sa.Integer(), nullable=True),
    sa.Column('end_step', sa.Integer(), nullable=True),
    sa.Column('skip_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_project_id'), 'pipeline_runs', ['project_id'], unique=False)
    op.create_table('project_style_guides',
    sa.Column('project_id', StringUUID(), nullable=False),
    sa.Column('voice_tone_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Voice/tone rules: dos, donts, examples'),
    sa.Column('tone_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Good/bad examples of tone'),
    sa.Column('forbidden_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Claims that should never be made'),
    sa.Column('compliance_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Industry-specific compliance notes'),
    sa.Column('legal_disclaimers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Required legal disclaimers'),
    sa.Column('formatting_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Heading styles, list formatting, etc.'),
    sa.Column('citation_style', sa.String(length=50), nullable=True, comment='Citation format (APA, Chicago, inline, etc.)'),
    sa.Column('base_qa_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Base QA items that apply to all content'),
    sa.Column('common_failure_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Common mistakes to watch for'),
    sa.Column('default_internal_linking_min', sa.Integer(), nullable=True, comment='Minimum internal links per article'),
    sa.Column('default_external_linking_min', sa.Integer(), nullable=True, comment='Minimum external links per article'),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_style_guides_project_id'), 'project_style_guides', ['project_id'], unique=True)
    op.create_table('seed_topics',
    sa.Column('project_id', StringUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pillar_type', sa.String(length=50), nullable=False),
    sa.Column('icp_relevance', sa.Text(), nullable=True),
    sa.Column('product_tie_in', sa.Text(), nullable=True),
    sa.Column('intended_content_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coverage_intent', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_topics_project_id'), 'seed_topics', ['project_id'], unique=False)
    op.create_table('step_executions',
    sa.Column('pipeline_run_id', StringUUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_total', sa.Integer(), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_executions_pipeline_run_id'), 'step_executions', ['pipeline_run_id'], unique=False)
    op.create_table('topics',
    sa.Column('project_id', StringUUID(), nullable=False),
    sa.Column('parent_topic_id', StringUUID(), nullable=True),
    sa.Column('pillar_seed_topic_id', StringUUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster_method', sa.String(length=50), nullable=True),
    sa.Column('cluster_coherence', sa.Float(), nullable=True),
    sa.Column('primary_keyword_id', StringUUID(), nullable=True),
    sa.Column('dominant_intent', sa.String(length=50), nullable=True),
    sa.Column('dominant_page_type', sa.String(length=50), nullable=True),
    sa.Column('funnel_stage', sa.String(length=20), nullable=True),
    sa.Column('total_volume', sa.Integer(), nullable=True),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('keyword_count', sa.Integer(), nullable=False),
    sa.Column('estimated_demand', sa.Integer(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_url_type', sa.String(length=50), nullable=True),
    sa.Column('recommended_publish_order', sa.Integer(), nullable=True),
    sa.Column('target_money_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_role', sa.String(length=50), nullable=True),
    sa.Column('cannibalization_risk', sa.Float(), nullable=True),
    sa.Column('overlapping_topic_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cluster_notes', sa.Text(), nullable=True),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pillar_seed_topic_id'], ['seed_topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_project_id'), 'topics', ['project_id'], unique=False)
    op.create_table('keywords',
    sa.Column('project_id', StringUUID(), nullable=False),
    sa.Column('seed_topic_id', StringUUID(), nullable=True),
    sa.Column('topic_id', StringUUID(), nullable=True),
    sa.Column('parent_keyword_id', StringUUID(), nullable=True),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('keyword_normalized', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_method', sa.String(length=100), nullable=True),
    sa.Column('raw_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exclusion_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('search_volume_period', sa.String(length=50), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('trend_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_data_source', sa.String(length=100), nullable=True),
    sa.Column('metrics_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics_confidence', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('recommended_page_type', sa.String(length=50), nullable=True),
    sa.Column('page_type_rationale', sa.Text(), nullable=True),
    sa.Column('funnel_stage', sa.String(length=20), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('serp_top_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('serp_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_intent', sa.String(length=50), nullable=True),
    sa.Column('validated_page_type', sa.String(length=50), nullable=True),
    sa.Column('format_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('serp_mismatch_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seed_topic_id'], ['seed_topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_keywords_keyword_normalized'), 'keywords', ['keyword_normalized'], unique=False)
    op.create_index(op.f('ix_keywords_project_id'), 'keywords', ['project_id'], unique=False)
    op.create_index(op.f('ix_keywords_seed_topic_id'), 'keywords', ['seed_topic_id'], unique=False)
    op.create_index(op.f('ix_keywords_topic_id'), 'keywords', ['topic_id'], unique=False)
    op.create_table('content_briefs',
    sa.Column('project_id', StringUUID(), nullable=False),
    sa.Column('topic_id', StringUUID(), nullable=False),
    sa.Column('target_keyword_id', StringUUID(), nullable=True),
    sa.Column('primary_keyword', sa.String(length=500), nullable=False),
    sa.Column('search_intent', sa.String(length=50), nullable=True),
    sa.Column('page_type', sa.String(length=50), nullable=True),
    sa.Column('funnel_stage', sa.String(length=20), nullable=True),
    sa.Column('working_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('reader_job_to_be_done', sa.Text(), nullable=True),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_keywords_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('examples_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faq_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_schema_type', sa.String(length=100), nullable=True),
    sa.Column('internal_links_out', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('internal_links_in', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('money_page_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_sources_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_title_guidelines', sa.Text(), nullable=True),
    sa.Column('meta_description_guidelines', sa.Text(), nullable=True),
    sa.Column('target_word_count_min', sa.Integer(), nullable=True),
    sa.Column('target_word_count_max', sa.Integer(), nullable=True),
    sa.Column('must_include_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_project_id'), 'content_briefs', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_topic_id'), 'content_briefs', ['topic_id'], unique=False)
    op.create_table('brief_deltas',
    sa.Column('style_guide_id', StringUUID(), nullable=False),
    sa.Column('brief_id', StringUUID(), nullable=False),
    sa.Column('page_type_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Rules specific to this page type'),
    sa.Column('must_include_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Required sections for this content type'),
    sa.Column('h1_h2_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Heading usage rules for this page type'),
    sa.Column('internal_linking_minimums', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Override linking minimums for this brief'),
    sa.Column('schema_type', sa.String(length=50), nullable=True, comment='Schema.org type (HowTo, FAQ, Article, etc.)'),
    sa.Column('schema_block_template', sa.Text(), nullable=True, comment='JSON-LD template for this content type'),
    sa.Column('link_placeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Placeholder markers for link insertion'),
    sa.Column('additional_qa_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra QA items specific to this brief'),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_guide_id'], ['project_style_guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_deltas_brief_id'), 'brief_deltas', ['brief_id'], unique=True)
    op.create_index(op.f('ix_brief_deltas_style_guide_id'), 'brief_deltas', ['style_guide_id'], unique=False)
    op.create_table('writer_instructions',
    sa.Column('brief_id', StringUUID(), nullable=False),
    sa.Column('voice_tone_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forbidden_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formatting_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('h1_h2_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('internal_linking_minimums', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_guidance', sa.Text(), nullable=True),
    sa.Column('snippet_ctr_guidelines', sa.Text(), nullable=True),
    sa.Column('qa_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pass_fail_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_failure_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link_placeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_block_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citation_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writer_instructions')
    op.drop_index(op.f('ix_brief_deltas_style_guide_id'), table_name='brief_deltas')
    op.drop_index(op.f('ix_brief_deltas_brief_id'), table_name='brief_deltas')
    op.drop_table('brief_deltas')
    op.drop_index(op.f('ix_content_briefs_topic_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_project_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_keywords_topic_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_seed_topic_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_project_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword_normalized'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_topics_project_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_step_executions_pipeline_run_id'), table_name='step_executions')
    op.drop_table('step_executions')
    op.drop_index(op.f('ix_seed_topics_project_id'), table_name='seed_topics')
    op.drop_table('seed_topics')
    op.drop_index(op.f('ix_project_style_guides_project_id'), table_name='project_style_guides')
    op.drop_table('project_style_guides')
    op.drop_index(op.f('ix_pipeline_runs_project_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('brand_profiles')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
